# Updates the emoji/glyph list in src/caelestia/data/emojis.txt

name: Update emojis

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout as app
        uses: caelestia-dots/.github/actions/app-checkout@main
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          commit-add: src/caelestia/data/emojis.txt
          commit-message: "chore(emoji): update emoji data [CI]"

      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Fetch emojis
        run: ./bin/caelestia emoji -f
