name: Update flake inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Update flake inputs
        uses: caelestia-dots/.github/actions/nix-update@main
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          package: with-shell

      - name: Test modules
        run: |
          result/bin/caelestia -v
          result/bin/caelestia -h
          result/bin/caelestia toggle -h
          result/bin/caelestia scheme -h
          result/bin/caelestia scheme list
          result/bin/caelestia scheme get
          result/bin/caelestia scheme set -n gruvbox -f hard -m dark -v content
          result/bin/caelestia screenshot -h
          result/bin/caelestia record -h
          result/bin/caelestia clipboard -h
          result/bin/caelestia emoji -h
          result/bin/caelestia emoji
          result/bin/caelestia wallpaper -h
          result/bin/caelestia resizer -h

      - name: Test graphical stuff
        env:
          XDG_RUNTIME_DIR: /home/runner/runtime
          WLR_BACKENDS: headless
          WLR_LIBINPUT_NO_DEVICES: 1
          WAYLAND_DISPLAY: wayland-1
          GTK_USE_PORTAL: 0
        run: |
          mkdir $XDG_RUNTIME_DIR
          chown $USER $XDG_RUNTIME_DIR
          chmod 0700 $XDG_RUNTIME_DIR

          nix profile install 'nixpkgs#sway'
          sway &
          sleep 3  # Give Sway some time to start
          result/bin/caelestia shell -d
          sleep 3  # Give the shell some time to start (and die)

          # Test CLI graphical modules
          result/bin/caelestia clipboard &
          result/bin/caelestia emoji -p &
          result/bin/caelestia shell -s
          result/bin/caelestia shell drawers list
          result/bin/caelestia shell mpris list
          result/bin/caelestia shell notifs clear

          pgrep .quickshell-wra  # Fail job if shell died
          result/bin/caelestia shell -k
          killall sway  # Screw using IPC
